const Accounting = {
  cash_disbursements: {
    tablename: 'cash_disbursements',
    prefix: 'cd',
    prefix_: 'cd_',
    insertColumns: [
      'vendor_id',
      'document_reference',
      'payment_date',
      'mode_of_payment',
      'bank_name',
      'check_number',
      'remarks',
      'total_amount_due',
      'state',
      'created_date',
      'created_by',
      'checked_by',
      'approved_by',
    ],
    selectColumns: [
      'cd_id',
      'cd_vendor_id',
      'cd_document_reference',
      'cd_payment_date',
      'cd_mode_of_payment',
      'cd_bank_name',
      'cd_check_number',
      'cd_remarks',
      'cd_total_amount_due',
      'cd_state',
      'cd_created_date',
      'cd_created_by',
      'cd_checked_by',
      'cd_approved_by',
    ],
    selectOptionColumns: {
      id: 'cd_id',
      vendor_id: 'cd_vendor_id',
      document_reference: 'cd_document_reference',
      payment_date: 'cd_payment_date',
      mode_of_payment: 'cd_mode_of_payment',
      bank_name: 'cd_bank_name',
      check_number: 'cd_check_number',
      remarks: 'cd_remarks',
      total_amount_due: 'cd_total_amount_due',
      state: 'cd_state',
      created_date: 'cd_created_date',
      created_by: 'cd_created_by',
      checked_by: 'cd_checked_by',
      approved_by: 'cd_approved_by',
    },
    updateOptionColumns: {
      id: 'id',
      vendor_id: 'vendor_id',
      document_reference: 'document_reference',
      payment_date: 'payment_date',
      mode_of_payment: 'mode_of_payment',
      bank_name: 'bank_name',
      check_number: 'check_number',
      remarks: 'remarks',
      total_amount_due: 'total_amount_due',
      state: 'state',
      created_date: 'created_date',
      created_by: 'created_by',
      checked_by: 'checked_by',
      approved_by: 'approved_by',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      vendor_id: 'INTEGER',
      document_reference: 'STRING',
      payment_date: 'STRING',
      mode_of_payment: 'STRING',
      bank_name: 'STRING',
      check_number: 'STRING',
      remarks: 'TEXT',
      total_amount_due: 'DECIMAL',
      state: 'ENUM',
      created_date: 'STRING',
      created_by: 'STRING',
      checked_by: 'STRING',
      approved_by: 'STRING',
    },
  },
  receipts: {
    tablename: 'receipts',
    prefix: 'r',
    prefix_: 'r_',
    insertColumns: [
      'customer_id',
      'document_reference',
      'collection_date',
      'mode_of_payment',
      'bank_name',
      'check_number',
      'remarks',
      'total_amount_due',
      'state',
      'created_date',
      'created_by',
      'checked_by',
      'approved_by',
    ],
    selectColumns: [
      'r_id',
      'r_customer_id',
      'r_document_reference',
      'r_collection_date',
      'r_mode_of_payment',
      'r_bank_name',
      'r_check_number',
      'r_remarks',
      'r_total_amount_due',
      'r_state',
      'r_created_date',
      'r_created_by',
      'r_checked_by',
      'r_approved_by',
    ],
    selectOptionColumns: {
      id: 'r_id',
      customer_id: 'r_customer_id',
      document_reference: 'r_document_reference',
      collection_date: 'r_collection_date',
      mode_of_payment: 'r_mode_of_payment',
      bank_name: 'r_bank_name',
      check_number: 'r_check_number',
      remarks: 'r_remarks',
      total_amount_due: 'r_total_amount_due',
      state: 'r_state',
      created_date: 'r_created_date',
      created_by: 'r_created_by',
      checked_by: 'r_checked_by',
      approved_by: 'r_approved_by',
    },
    updateOptionColumns: {
      id: 'id',
      customer_id: 'customer_id',
      document_reference: 'document_reference',
      collection_date: 'collection_date',
      mode_of_payment: 'mode_of_payment',
      bank_name: 'bank_name',
      check_number: 'check_number',
      remarks: 'remarks',
      total_amount_due: 'total_amount_due',
      state: 'state',
      created_date: 'created_date',
      created_by: 'created_by',
      checked_by: 'checked_by',
      approved_by: 'approved_by',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      customer_id: 'INTEGER',
      document_reference: 'STRING',
      collection_date: 'STRING',
      mode_of_payment: 'STRING',
      bank_name: 'STRING',
      check_number: 'STRING',
      remarks: 'TEXT',
      total_amount_due: 'DECIMAL',
      state: 'ENUM',
      created_date: 'STRING',
      created_by: 'STRING',
      checked_by: 'STRING',
      approved_by: 'STRING',
    },
  },
  sales: {
    tablename: 'sales',
    prefix: 's',
    prefix_: 's_',
    insertColumns: [
      'customer_id',
      'document_reference',
      'terms',
      'date_delivered',
      'date_due',
      'remarks',
      'total_amount_due',
      'status',
      'state',
      'created_date',
      'created_by',
      'checked_by',
      'approved_by',
    ],
    selectColumns: [
      's_id',
      's_customer_id',
      's_document_reference',
      's_terms',
      's_date_delivered',
      's_date_due',
      's_remarks',
      's_total_amount_due',
      's_status',
      's_state',
      's_created_date',
      's_created_by',
      's_checked_by',
      's_approved_by',
    ],
    selectOptionColumns: {
      id: 's_id',
      customer_id: 's_customer_id',
      document_reference: 's_document_reference',
      terms: 's_terms',
      date_delivered: 's_date_delivered',
      date_due: 's_date_due',
      remarks: 's_remarks',
      total_amount_due: 's_total_amount_due',
      status: 's_status',
      state: 's_state',
      created_date: 's_created_date',
      created_by: 's_created_by',
      checked_by: 's_checked_by',
      approved_by: 's_approved_by',
    },
    updateOptionColumns: {
      id: 'id',
      customer_id: 'customer_id',
      document_reference: 'document_reference',
      terms: 'terms',
      date_delivered: 'date_delivered',
      date_due: 'date_due',
      remarks: 'remarks',
      total_amount_due: 'total_amount_due',
      status: 'status',
      state: 'state',
      created_date: 'created_date',
      created_by: 'created_by',
      checked_by: 'checked_by',
      approved_by: 'approved_by',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      customer_id: 'INTEGER',
      document_reference: 'STRING',
      terms: 'ENUM',
      date_delivered: 'STRING',
      date_due: 'STRING',
      remarks: 'TEXT',
      total_amount_due: 'DECIMAL',
      status: 'ENUM',
      state: 'ENUM',
      created_date: 'STRING',
      created_by: 'STRING',
    },
  },
  collections: {
    tablename: 'collections',
    prefix: 'c',
    prefix_: 'c_',
    insertColumns: [
      'customer_id',
      'document_reference',
      'mode_of_payment',
      'bank_name',
      'check_number',
      'collection_date',
      'remarks',
      'state',
      'created_date',
      'created_by',
      'checked_by',
      'approved_by',
    ],
    selectColumns: [
      'c_id',
      'c_customer_id',
      'c_document_reference',
      'c_mode_of_payment',
      'c_bank_name',
      'c_check_number',
      'c_collection_date',
      'c_remarks',
      'c_state',
      'c_created_date',
      'c_created_by',
      'c_checked_by',
      'c_approved_by',
    ],
    selectOptionColumns: {
      id: 'c_id',
      customer_id: 'c_customer_id',
      document_reference: 'c_document_reference',
      mode_of_payment: 'c_mode_of_payment',
      bank_name: 'c_bank_name',
      check_number: 'c_check_number',
      collection_date: 'c_collection_date',
      remarks: 'c_remarks',
      state: 'c_state',
      created_date: 'c_created_date',
      created_by: 'c_created_by',
      checked_by: 'c_checked_by',
      approved_by: 'c_approved_by',
    },
    updateOptionColumns: {
      id: 'id',
      customer_id: 'customer_id',
      document_reference: 'document_reference',
      mode_of_payment: 'mode_of_payment',
      bank_name: 'bank_name',
      check_number: 'check_number',
      collection_date: 'collection_date',
      remarks: 'remarks',
      state: 'state',
      created_date: 'created_date',
      created_by: 'created_by',
      checked_by: 'checked_by',
      approved_by: 'approved_by',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      customer_id: 'INTEGER',
      document_reference: 'STRING',
      mode_of_payment: 'ENUM',
      bank_name: 'STRING',
      check_number: 'TEXT',
      collection_date: 'STRING',
      remarks: 'TEXT',
      state: 'ENUM',
      created_date: 'STRING',
      created_by: 'STRING',
      checked_by: 'STRING',
      approved_by: 'STRING',
    },
  },
  purchase: {
    tablename: 'purchase',
    prefix: 'p',
    prefix_: 'p_',
    insertColumns: [
      'vendor_id',
      'document_reference',
      'terms',
      'date_delivered',
      'date_due',
      'remarks',
      'total_amount_due',
      'status',
      'state',
      'created_date',
      'created_by',
      'checked_by',
      'approved_by',
    ],
    selectColumns: [
      'p_id',
      'p_vendor_id',
      'p_document_reference',
      'p_terms',
      'p_date_delivered',
      'p_date_due',
      'p_remarks',
      'p_total_amount_due',
      'p_status',
      'p_state',
      'p_created_date',
      'p_created_by',
      'p_checked_by',
      'p_approved_by',
    ],
    selectOptionColumns: {
      id: 'p_id',
      vendor_id: 'p_vendor_id',
      document_reference: 'p_document_reference',
      terms: 'p_terms',
      date_delivered: 'p_date_delivered',
      date_due: 'p_date_due',
      remarks: 'p_remarks',
      total_amount_due: 'p_total_amount_due',
      status: 'p_status',
      state: 'p_state',
      created_date: 'p_created_date',
      created_by: 'p_created_by',
      checked_by: 'p_checked_by',
      approved_by: 'p_approved_by',
    },
    updateOptionColumns: {
      id: 'id',
      vendor_id: 'vendor_id',
      document_reference: 'document_reference',
      terms: 'terms',
      date_delivered: 'date_delivered',
      date_due: 'date_due',
      remarks: 'remarks',
      total_amount_due: 'total_amount_due',
      status: 'status',
      state: 'state',
      created_date: 'created_date',
      created_by: 'created_by',
      checked_by: 'checked_by',
      approved_by: 'approved_by',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      vendor_id: 'INTEGER',
      document_reference: 'STRING',
      terms: 'ENUM',
      date_delivered: 'STRING',
      date_due: 'STRING',
      remarks: 'TEXT',
      total_amount_due: 'DECIMAL',
      status: 'ENUM',
      state: 'ENUM',
      created_date: 'STRING',
      created_by: 'STRING',
      checked_by: 'STRING',
      approved_by: 'STRING',
    },
  },
  purchase_items: {
    tablename: 'purchase_items',
    prefix: 'pi',
    prefix_: 'pi_',
    insertColumns: [
      'purchase_id',
      'product_service',
      'charts_of_accounts',
      'description',
      'quantity',
      'purchase_price',
      'discount',
      'discount_type',
      'vat',
      'witholding_tax',
      'responsibility_center',
    ],
    selectColumns: [
      'pi_id',
      'pi_purchase_id',
      'pi_product_service',
      'pi_charts_of_accounts',
      'pi_description',
      'pi_quantity',
      'pi_purchase_price',
      'pi_discount',
      'pi_discount_type',
      'pi_vat',
      'pi_witholding_tax',
      'pi_responsibility_center',
    ],
    selectOptionColumns: {
      id: 'pi_id',
      purchase_id: 'pi_purchase_id',
      product_service: 'pi_product_service',
      charts_of_accounts: 'pi_charts_of_accounts',
      description: 'pi_description',
      quantity: 'pi_quantity',
      purchase_price: 'pi_purchase_price',
      discount: 'pi_discount',
      discount_type: 'pi_discount_type',
      vat: 'pi_vat',
      withholding_tax: 'pi_witholding_tax',
      responsibility_center: 'pi_responsibility_center',
    },
    updateOptionColumns: {
      id: 'id',
      purchase_id: 'purchase_id',
      product_service: 'product_service',
      charts_of_accounts: 'charts_of_accounts',
      description: 'description',
      quantity: 'quantity',
      purchase_price: 'purchase_price',
      discount: 'discount',
      discount_type: 'discount_type',
      vat: 'vat',
      withholding_tax: 'witholding_tax',
      responsibility_center: 'responsibility_center',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      purchase_id: 'INTEGER',
      product_service: 'STRING',
      charts_of_accounts: 'INTEGER',
      description: 'TEXT',
      quantity: 'INTEGER',
      purchase_price: 'DECIMAL',
      discount: 'DECIMAL',
      discount_type: 'STRING',
      vat: 'DECIMAL',
      withholding_tax: 'DECIMAL',
      responsibility_center: 'STRING',
    },
  },
  purchase_attachments: {
    tablename: 'purchase_attachments',
    prefix: 'pa',
    prefix_: 'pa_',
    insertColumns: [
      'purchase_id',
      'file',
      'name',
      'remarks',
      'uploaded_by',
      'uploaded_date',
    ],
    selectColumns: [
      'pa_id',
      'pa_purchase_id',
      'pa_file',
      'pa_name',
      'pa_remarks',
      'pa_uploaded_by',
      'pa_uploaded_date',
    ],
    selectOptionColumns: {
      id: 'pa_id',
      purchase_id: 'pa_purchase_id',
      file: 'pa_file',
      name: 'pa_name',
      remarks: 'pa_remarks',
      uploaded_by: 'pa_uploaded_by',
      uploaded_date: 'pa_uploaded_date',
    },
    updateOptionColumns: {
      id: 'id',
      purchase_id: 'purchase_id',
      file: 'file',
      name: 'name',
      remarks: 'remarks',
      uploaded_by: 'uploaded_by',
      uploaded_date: 'uploaded_date',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      purchase_id: 'INTEGER',
      file: 'TEXT',
      name: 'STRING',
      remarks: 'TEXT',
      uploaded_by: 'STRING',
      uploaded_date: 'STRING',
    },
  },
  cash_disbursement_items: {
    tablename: 'cash_disbursement_items',
    prefix: 'cdi',
    prefix_: 'cdi_',
    insertColumns: [
      'cash_disbursement_id',
      'product_service',
      'charts_of_accounts',
      'description',
      'quantity',
      'purchase_price',
      'discount',
      'discount_type',
      'vat',
      'witholding_tax',
      'responsibility_center',
    ],
    selectColumns: [
      'cdi_id',
      'cdi_cash_disbursement_id',
      'cdi_product_service',
      'cdi_charts_of_accounts',
      'cdi_description',
      'cdi_quantity',
      'cdi_purchase_price',
      'cdi_discount',
      'cdi_discount_type',
      'cdi_vat',
      'cdi_witholding_tax',
      'cdi_responsibility_center',
    ],
    selectOptionColumns: {
      id: 'cdi_id',
      cash_disbursement_id: 'cdi_cash_disbursement_id',
      product_service: 'cdi_product_service',
      charts_of_accounts: 'cdi_charts_of_accounts',
      description: 'cdi_description',
      quantity: 'cdi_quantity',
      purchase_price: 'cdi_purchase_price',
      discount: 'cdi_discount',
      discount_type: 'cdi_discount_type',
      vat: 'cdi_vat',
      witholding_tax: 'cdi_witholding_tax',
      responsibility_center: 'cdi_responsibility_center',
    },
    updateOptionColumns: {
      id: 'id',
      cash_disbursement_id: 'cash_disbursement_id',
      product_service: 'product_service',
      charts_of_accounts: 'charts_of_accounts',
      description: 'description',
      quantity: 'quantity',
      purchase_price: 'purchase_price',
      discount: 'discount',
      discount_type: 'discount_type',
      vat: 'vat',
      witholding_tax: 'witholding_tax',
      responsibility_center: 'responsibility_center',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      cash_disbursement_id: 'INTEGER',
      product_service: 'STRING',
      charts_of_accounts: 'INTEGER',
      description: 'TEXT',
      quantity: 'INTEGER',
      purchase_price: 'DECIMAL',
      discount: 'DECIMAL',
      discount_type: 'STRING',
      vat: 'DECIMAL',
      witholding_tax: 'DECIMAL',
      responsibility_center: 'STRING',
    },
  },
  receipt_items: {
    tablename: 'receipt_items',
    prefix: 'ri',
    prefix_: 'ri_',
    insertColumns: [
      'receipts_id',
      'product_service',
      'charts_of_accounts',
      'description',
      'quantity',
      'sales_price',
      'discount',
      'discount_type',
      'vat',
      'witholding_tax',
      'responsibility_center',
    ],
    selectColumns: [
      'ri_id',
      'ri_receipts_id',
      'ri_product_service',
      'ri_charts_of_accounts',
      'ri_description',
      'ri_quantity',
      'ri_sales_price',
      'ri_discount',
      'ri_discount_type',
      'ri_vat',
      'ri_witholding_tax',
      'ri_responsibility_center',
    ],
    selectOptionColumns: {
      id: 'ri_id',
      receipts_id: 'ri_receipts_id',
      product_service: 'ri_product_service',
      charts_of_accounts: 'ri_charts_of_accounts',
      description: 'ri_description',
      quantity: 'ri_quantity',
      sales_price: 'ri_sales_price',
      discount: 'ri_discount',
      discount_type: 'ri_discount_type',
      vat: 'ri_vat',
      withholding_tax: 'ri_witholding_tax',
      responsibility_center: 'ri_responsibility_center',
    },
    updateOptionColumns: {
      id: 'id',
      receipts_id: 'receipts_id',
      product_service: 'product_service',
      charts_of_accounts: 'charts_of_accounts',
      description: 'description',
      quantity: 'quantity',
      sales_price: 'sales_price',
      discount: 'discount',
      discount_type: 'discount_type',
      vat: 'vat',
      witholding_tax: 'witholding_tax',
      responsibility_center: 'responsibility_center',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      receipts_id: 'INTEGER',
      product_service: 'STRING',
      charts_of_accounts: 'INTEGER',
      description: 'TEXT',
      quantity: 'INTEGER',
      sales_price: 'DECIMAL',
      discount: 'DECIMAL',
      discount_type: 'STRING',
      vat: 'DECIMAL',
      witholding_tax: 'DECIMAL',
      responsibility_center: 'STRING',
    },
  },
  sales_items: {
    tablename: 'sales_items',
    prefix: 'si',
    prefix_: 'si_',
    insertColumns: [
      'sales_id',
      'product_service',
      'charts_of_accounts',
      'description',
      'quantity',
      'sales_price',
      'discount',
      'discount_type',
      'vat',
      'witholding_tax',
      'responsibility_center',
    ],
    selectColumns: [
      'si_id',
      'si_sales_id',
      'si_product_service',
      'si_charts_of_accounts',
      'si_description',
      'si_quantity',
      'si_sales_price',
      'si_discount',
      'si_discount_type',
      'si_vat',
      'si_witholding_tax',
      'si_responsibility_center',
    ],
    selectOptionColumns: {
      id: 'si_id',
      sales_id: 'si_sales_id',
      product_service: 'si_product_service',
      charts_of_accounts: 'si_charts_of_accounts',
      description: 'si_description',
      quantity: 'si_quantity',
      sales_price: 'si_sales_price',
      discount: 'si_discount',
      discount_type: 'si_discount_type',
      vat: 'si_vat',
      witholding_tax: 'si_witholding_tax',
      responsibility_center: 'si_responsibility_center',
    },
    updateOptionColumns: {
      id: 'id',
      sales_id: 'sales_id',
      product_service: 'product_service',
      charts_of_accounts: 'charts_of_accounts',
      description: 'description',
      quantity: 'quantity',
      sales_price: 'sales_price',
      discount: 'discount',
      discount_type: 'discount_type',
      vat: 'vat',
      witholding_tax: 'witholding_tax',
      responsibility_center: 'responsibility_center',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      sales_id: 'INTEGER',
      product_service: 'STRING',
      charts_of_accounts: 'INTEGER',
      description: 'TEXT',
      quantity: 'INTEGER',
      sales_price: 'DECIMAL',
      discount: 'DECIMAL',
      discount_type: 'STRING',
      vat: 'DECIMAL',
      witholding_tax: 'DECIMAL',
      responsibility_center: 'STRING',
    },
  },
  collection_items: {
    tablename: 'collection_items',
    prefix: 'ci',
    prefix_: 'ci_',
    insertColumns: ['collection_id', 'sales_id', 'amount', 'witholding_tax'],
    selectColumns: [
      'ci_id',
      'ci_collection_id',
      'ci_sales_id',
      'ci_amount',
      'ci_withholding_tax',
    ],
    selectOptionColumns: {
      id: 'ci_id',
      collection_id: 'ci_collection_id',
      sales_id: 'ci_sales_id',
      amount: 'ci_amount',
      witholding_tax: 'ci_withholding_tax',
    },
    updateOptionColumns: {
      id: 'id',
      collection_id: 'collection_id',
      sales_id: 'sales_id',
      amount: 'amount',
      witholding_tax: 'witholding_tax',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      collection_id: 'INTEGER',
      sales_id: 'INTEGER',
      amount: 'DECIMAL',
      witholding_tax: 'DECIMAL',
    },
  },
  cash_disbursement_attachments: {
    tablename: 'cash_disbursement_attachments',
    prefix: 'a',
    prefix_: 'a_',
    insertColumns: [
      'cash_disburssement_id',
      'file',
      'name',
      'remarks',
      'uploaded_by',
      'uploaded_date',
    ],
    selectColumns: [
      'a_id',
      'a_cash_disburssement_id',
      'a_file',
      'a_name',
      'a_remarks',
      'a_uploaded_by',
      'a_uploaded_date',
    ],
    selectOptionColumns: {
      id: 'a_id',
      cash_disburssement_id: 'a_cash_disburssement_id',
      file: 'a_file',
      name: 'a_name',
      remarks: 'a_remarks',
      uploaded_by: 'a_uploaded_by',
      uploaded_date: 'a_uploaded_date',
    },
    updateOptionColumns: {
      id: 'id',
      cash_disburssement_id: 'cash_disburssement_id',
      file: 'file',
      name: 'name',
      remarks: 'remarks',
      uploaded_by: 'uploaded_by',
      uploaded_date: 'uploaded_date',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      cash_disburssement_id: 'INTEGER',
      file: 'TEXT',
      name: 'STRING',
      remarks: 'TEXT',
      uploaded_by: 'STRING',
      uploaded_date: 'STRING',
    },
  },
  receipt_attachments: {
    tablename: 'receipt_attachments',
    prefix: 'ra',
    prefix_: 'ra_',
    insertColumns: [
      'receipt_id',
      'file',
      'name',
      'remarks',
      'uploaded_by',
      'uploaded_date',
    ],
    selectColumns: [
      'ra_id',
      'ra_receipt_id',
      'ra_file',
      'ra_name',
      'ra_remarks',
      'ra_uploaded_by',
      'ra_uploaded_date',
    ],
    selectOptionColumns: {
      id: 'ra_id',
      receipt_id: 'ra_receipt_id',
      file: 'ra_file',
      name: 'ra_name',
      remarks: 'ra_remarks',
      uploaded_by: 'ra_uploaded_by',
      uploaded_date: 'ra_uploaded_date',
    },
    updateOptionColumns: {
      id: 'id',
      receipt_id: 'receipt_id',
      file: 'file',
      name: 'name',
      remarks: 'remarks',
      uploaded_by: 'uploaded_by',
      uploaded_date: 'uploaded_date',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      receipt_id: 'INTEGER',
      file: 'TEXT',
      name: 'STRING',
      remarks: 'TEXT',
      uploaded_by: 'STRING',
      uploaded_date: 'STRING',
    },
  },
  sales_attachments: {
    tablename: 'sales_attachments',
    prefix: 'sa',
    prefix_: 'sa_',
    insertColumns: [
      'sales_id',
      'file',
      'name',
      'remarks',
      'uploaded_by',
      'uploaded_date',
    ],
    selectColumns: [
      'sa_id',
      'sa_sales_id',
      'sa_file',
      'sa_name',
      'sa_remarks',
      'sa_uploaded_by',
      'sa_uploaded_date',
    ],
    selectOptionColumns: {
      id: 'sa_id',
      sales_id: 'sa_sales_id',
      file: 'sa_file',
      name: 'sa_name',
      remarks: 'sa_remarks',
      uploaded_by: 'sa_uploaded_by',
      uploaded_date: 'sa_uploaded_date',
    },
    updateOptionColumns: {
      id: 'id',
      sales_id: 'sales_id',
      file: 'file',
      name: 'name',
      remarks: 'remarks',
      uploaded_by: 'uploaded_by',
      uploaded_date: 'uploaded_date',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      sales_id: 'INTEGER',
      file: 'TEXT',
      name: 'STRING',
      remarks: 'TEXT',
      uploaded_by: 'STRING',
      uploaded_date: 'STRING',
    },
  },
  collection_attachments: {
    tablename: 'collection_attachments',
    prefix: 'ca',
    prefix_: 'ca_',
    insertColumns: [
      'collection_id',
      'file',
      'name',
      'remarks',
      'uploaded_by',
      'uploaded_date',
    ],
    selectColumns: [
      'ca_id',
      'ca_collection_id',
      'ca_file',
      'ca_name',
      'ca_remarks',
      'ca_uploaded_by',
      'ca_uploaded_date',
    ],
    selectOptionColumns: {
      id: 'ca_id',
      collection_id: 'ca_collection_id',
      file: 'ca_file',
      name: 'ca_name',
      remarks: 'ca_remarks',
      uploaded_by: 'ca_uploaded_by',
      uploaded_date: 'ca_uploaded_date',
    },
    updateOptionColumns: {
      id: 'id',
      collection_id: 'collection_id',
      file: 'file',
      name: 'name',
      remarks: 'remarks',
      uploaded_by: 'uploaded_by',
      uploaded_date: 'uploaded_date',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      collection_id: 'INTEGER',
      file: 'TEXT',
      name: 'STRING',
      remarks: 'TEXT',
      uploaded_by: 'STRING',
      uploaded_date: 'STRING',
    },
  },
  journal_entries: {
    tablename: 'journal_entries',
    prefix: 'je',
    prefix_: 'je_',
    insertColumns: [
      'db_name',
      'db_id',
      'coa_id',
      'responsibility_center',
      'type',
      'amount',
      'date',
    ],
    selectColumns: [
      'je_id',
      'je_db_name',
      'je_db_id',
      'je_coa_id',
      'je_responsibility_center',
      'je_type',
      'je_amount',
      'je_date',
    ],
    selectOptionColumns: {
      id: 'je_id',
      db_name: 'je_db_name',
      db_id: 'je_db_id',
      coa_id: 'je_coa_id',
      responsibility_center: 'je_responsibility_center',
      type: 'je_type',
      amount: 'je_amount',
      date: 'je_date',
    },
    updateOptionColumns: {
      id: 'id',
      db_name: 'db_name',
      db_id: 'db_id',
      coa_id: 'coa_id',
      responsibility_center: 'responsibility_center',
      type: 'type',
      amount: 'amount',
      date: 'date',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      db_name: 'STRING',
      db_id: 'INTEGER',
      coa_id: 'INTEGER',
      responsibility_center: 'STRING',
      type: 'ENUM',
      amount: 'DECIMAL',
      date: 'STRING',
    },
  },
  payments: {
    tablename: 'payments',
    prefix: 'c',
    prefix_: 'c_',
    insertColumns: [
      'vendor_id',
      'document_reference',
      'mode_of_payment',
      'bank_name',
      'check_number',
      'payment_date',
      'remarks',
      'state',
      'created_date',
      'created_by',
      'checked_by',
      'approved_by',
    ],
    selectColumns: [
      'c_id',
      'c_vendor_id',
      'c_document_reference',
      'c_mode_of_payment',
      'c_bank_name',
      'c_check_number',
      'c_payment_date',
      'c_remarks',
      'c_state',
      'c_created_date',
      'c_created_by',
      'c_checked_by',
      'c_approved_by',
    ],
    selectOptionColumns: {
      id: 'c_id',
      vendor_id: 'c_vendor_id',
      document_reference: 'c_document_reference',
      mode_of_payment: 'c_mode_of_payment',
      bank_name: 'c_bank_name',
      check_number: 'c_check_number',
      payment_date: 'c_payment_date',
      remarks: 'c_remarks',
      state: 'c_state',
      created_date: 'c_created_date',
      created_by: 'c_created_by',
      checked_by: 'c_checked_by',
      approved_by: 'c_approved_by',
    },
    updateOptionColumns: {
      id: 'id',
      vendor_id: 'vendor_id',
      document_reference: 'document_reference',
      mode_of_payment: 'mode_of_payment',
      bank_name: 'bank_name',
      check_number: 'check_number',
      payment_date: 'payment_date',
      remarks: 'remarks',
      state: 'state',
      created_date: 'created_date',
      created_by: 'created_by',
      checked_by: 'checked_by',
      approved_by: 'approved_by',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      vendor_id: 'INTEGER',
      document_reference: 'STRING',
      mode_of_payment: 'ENUM',
      bank_name: 'STRING',
      check_number: 'TEXT',
      payment_date: 'STRING',
      remarks: 'TEXT',
      state: 'ENUM',
      created_date: 'STRING',
      created_by: 'STRING',
      checked_by: 'STRING',
      approved_by: 'STRING',
    },
  },
  payment_items: {
    tablename: 'payment_items',
    prefix: 'ci',
    prefix_: 'ci_',
    insertColumns: ['payment_id', 'purchase_id', 'amount', 'witholding_tax'],
    selectColumns: [
      'ci_id',
      'ci_payment_id',
      'ci_purchase_id',
      'ci_amount',
      'ci_witholding_tax',
    ],
    selectOptionColumns: {
      id: 'ci_id',
      payment_id: 'ci_payment_id',
      purchase_id: 'ci_purchase_id',
      amount: 'ci_amount',
      witholding_tax: 'ci_witholding_tax',
    },
    updateOptionColumns: {
      id: 'id',
      payment_id: 'payment_id',
      purchase_id: 'purchase_id',
      amount: 'amount',
      witholding_tax: 'witholding_tax',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      payment_id: 'INTEGER',
      purchase_id: 'INTEGER',
      amount: 'DECIMAL',
      witholding_tax: 'DECIMAL',
    },
  },
  payment_attachments: {
    tablename: 'payment_attachments',
    prefix: 'ca',
    prefix_: 'ca_',
    insertColumns: [
      'payment_id',
      'file',
      'name',
      'remarks',
      'uploaded_by',
      'uploaded_date',
    ],
    selectColumns: [
      'ca_id',
      'ca_payment_id',
      'ca_file',
      'ca_name',
      'ca_remarks',
      'ca_uploaded_by',
      'ca_uploaded_date',
    ],
    selectOptionColumns: {
      id: 'ca_id',
      payment_id: 'ca_payment_id',
      file: 'ca_file',
      name: 'ca_name',
      remarks: 'ca_remarks',
      uploaded_by: 'ca_uploaded_by',
      uploaded_date: 'ca_uploaded_date',
    },
    updateOptionColumns: {
      id: 'id',
      payment_id: 'payment_id',
      file: 'file',
      name: 'name',
      remarks: 'remarks',
      uploaded_by: 'uploaded_by',
      uploaded_date: 'uploaded_date',
    },
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      payment_id: 'INTEGER',
      file: 'TEXT',
      name: 'STRING',
      remarks: 'TEXT',
      uploaded_by: 'STRING',
      uploaded_date: 'STRING',
    },
  },
  adjustments: {
    tablename: 'adjustments',
    prefix: 'a',
    prefix_: 'a_',
    insertColumns: [
      'document_reference',
      'posting_date',
      'remarks',
      'status',
      'total_amount',
      'created_date',
      'created_by',
      'checked_by',
      'approved_by',
    ],
    selectColumns: [
      'a_id',
      'a_document_reference',
      'a_posting_date',
      'a_remarks',
      'a_status',
      'a_total_amount',
      'a_created_date',
      'a_created_by',
      'a_checked_by',
      'a_approved_by',
    ],
    selectOptionColumns: {
      id: 'a_id',
      document_reference: 'a_document_reference',
      posting_date: 'a_posting_date',
      remarks: 'a_remarks',
      status: 'a_status',
      total_amount: 'a_total_amount',
      created_date: 'a_created_date',
      created_by: 'a_created_by',
      checked_by: 'a_checked_by',
      approved_by: 'a_approved_by',
    },
    updateOptionColumns: {
      id: 'id',
      document_reference: 'document_reference',
      posting_date: 'posting_date',
      remarks: 'remarks',
      status: 'status',
      total_amount: 'total_amount',
      created_date: 'created_date',
      created_by: 'created_by',
      checked_by: 'checked_by',
      approved_by: 'approved_by',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      document_reference: 'STRING',
      posting_date: 'STRING',
      remarks: 'TEXT',
      status: 'ENUM',
      total_amount: 'DECIMAL',
      created_date: 'STRING',
      created_by: 'STRING',
      checked_by: 'STRING',
      approved_by: 'STRING',
    },
  },
  adjustment_attachments: {
    tablename: 'adjustment_attachments',
    prefix: 'aa',
    prefix_: 'aa_',
    insertColumns: [
      'adjustment_id',
      'file',
      'name',
      'remarks',
      'uploaded_by',
      'uploaded_date',
    ],
    selectColumns: [
      'aa_id',
      'aa_adjustment_id',
      'aa_file',
      'aa_name',
      'aa_remarks',
      'aa_uploaded_by',
      'aa_uploaded_date',
    ],
    selectOptionColumns: {
      id: 'aa_id',
      adjustment_id: 'aa_adjustment_id',
      file: 'aa_file',
      name: 'aa_name',
      remarks: 'aa_remarks',
      uploaded_by: 'aa_uploaded_by',
      uploaded_date: 'aa_uploaded_date',
    },
    updateOptionColumns: {
      id: 'id',
      adjustment_id: 'adjustment_id',
      file: 'file',
      name: 'name',
      remarks: 'remarks',
      uploaded_by: 'uploaded_by',
      uploaded_date: 'uploaded_date',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      adjustment_id: 'INTEGER',
      file: 'TEXT',
      name: 'STRING',
      remarks: 'TEXT',
      uploaded_by: 'STRING',
      uploaded_date: 'STRING',
    },
  },
  bank_reconciliation: {
    tablename: 'bank_reconciliation',
    prefix: 'br',
    prefix_: 'br_',
    insertColumns: ['bank_account', 'coa_id', 'running_balance'],
    selectColumns: ['br_id', 'br_bank_account', 'br_coa_id', 'br_running_balance'],
    selectOptionColumns: {
      id: 'br_id',
      bank_account: 'br_bank_account',
      coa_id: 'br_coa_id',
      running_balance: 'br_running_balance',
    },
    updateOptionColumns: {
      id: 'id',
      bank_account: 'bank_account',
      coa_id: 'coa_id',
      running_balance: 'running_balance',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      bank_account: 'STRING',
      coa_id: 'INTEGER',
      running_balance: 'DECIMAL',
    },
  },
  bank_reconciliation_items: {
    tablename: 'bank_reconciliation_items',
    prefix: 'bri',
    prefix_: 'bri_',
    insertColumns: [
      'br_id',
      'date',
      'description',
      'reference_number',
      'details',
      'debit',
      'credit',
      'balance',
      'created_by',
    ],
    selectColumns: [
      'bri_id',
      'bri_br_id',
      'bri_date',
      'bri_description',
      'bri_reference_number',
      'bri_details',
      'bri_debit',
      'bri_credit',
      'bri_balance',
      'bri_created_by',
    ],
    selectOptionColumns: {
      id: 'bri_id',
      br_id: 'bri_br_id',
      date: 'bri_date',
      description: 'bri_description',
      reference_number: 'bri_reference_number',
      details: 'bri_details',
      debit: 'bri_debit',
      credit: 'bri_credit',
      balance: 'bri_balance',
      created_by: 'bri_created_by',
    },
    updateOptionColumns: {
      id: 'id',
      br_id: 'br_id',
      date: 'date',
      description: 'description',
      reference_number: 'reference_number',
      details: 'details',
      debit: 'debit',
      credit: 'credit',
      balance: 'balance',
      created_by: 'created_by',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      br_id: 'INTEGER',
      date: 'DATE',
      description: 'TEXT',
      reference_number: 'STRING',
      details: 'TEXT',
      debit: 'DECIMAL',
      credit: 'DECIMAL',
      balance: 'DECIMAL',
      created_by: 'STRING',
    },
  },
  adjustment_balance: {
    tablename: 'adjustment_balance',
    prefix: 'ab',
    prefix_: 'ab_',
    insertColumns: [
      'br_id',
      'date',
      'type',
      'description',
      'amount',
      'side',
      'created_by',
    ],
    selectColumns: [
      'ab_id',
      'ab_br_id',
      'ab_date',
      'ab_type',
      'ab_description',
      'ab_amount',
      'ab_side',
      'ab_created_by',
    ],
    selectOptionColumns: {
      id: 'ab_id',
      br_id: 'ab_br_id',
      date: 'ab_date',
      type: 'ab_type',
      description: 'ab_description',
      amount: 'ab_amount',
      side: 'ab_side',
      created_by: 'ab_created_by',
    },
    updateOptionColumns: {
      id: 'id',
      br_id: 'br_id',
      date: 'date',
      type: 'type',
      description: 'description',
      amount: 'amount',
      side: 'side',
      created_by: 'created_by',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      br_id: 'INTEGER',
      date: 'DATE',
      type: 'STRING',
      description: 'TEXT',
      amount: 'DECIMAL',
      side: 'ENUM',
      created_by: 'STRING',
    },
  },
  bank_reconciliation_summary: {
    tablename: 'bank_reconciliation_summary',
    prefix: 'brs',
    prefix_: 'brs_',
    insertColumns: [
      'br_id',
      'start_date',
      'end_date',
      'adjusted_bank_balance',
      'adjusted_book_balance',
      'final_output',
      'prepared_by',
    ],
    selectColumns: [
      'brs_id',
      'brs_br_id',
      'brs_start_date',
      'brs_end_date',
      'brs_adjusted_bank_balance',
      'brs_adjusted_book_balance',
      'brs_final_output',
      'brs_prepared_by',
      'brs_created_date',
    ],
    selectOptionColumns: {
      id: 'brs_id',
      br_id: 'brs_br_id',
      start_date: 'brs_start_date',
      end_date: 'brs_end_date',
      adjusted_bank_balance: 'brs_adjusted_bank_balance',
      adjusted_book_balance: 'brs_adjusted_book_balance',
      final_output: 'brs_final_output',
      prepared_by: 'brs_prepared_by',
      created_date: 'brs_created_date',
    },
    updateOptionColumns: {
      id: 'id',
      br_id: 'br_id',
      start_date: 'start_date',
      end_date: 'end_date',
      adjusted_bank_balance: 'adjusted_bank_balance',
      adjusted_book_balance: 'adjusted_book_balance',
      final_output: 'final_output',
      prepared_by: 'prepared_by',
    },
    selectDateFormatColumns: {},
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      br_id: 'INTEGER',
      start_date: 'DATE',
      end_date: 'DATE',
      adjusted_bank_balance: 'DECIMAL',
      adjusted_book_balance: 'DECIMAL',
      final_output: 'TEXT',
      prepared_by: 'STRING',
      created_date: 'DATE',
    },
  },
}

exports.Accounting = Accounting
