
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const MasterUserSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	fullname: Joi.string().trim().required().messages({
        'any.required': 'fullname is required.',
        'string.empty': 'fullname must be a valid string.',
      }),
 	username: Joi.string().trim().required().messages({
        'any.required': 'username is required.',
        'string.empty': 'username must be a valid string.',
      }),
 	password: Joi.string().trim().required().messages({
        'any.required': 'password is required.',
        'string.empty': 'password must be a valid text.',
      }),
 	accessId: Joi.number().integer().required().messages({
        'any.required': 'accessId is required.',
        'number.base': 'accessId must be a valid integer.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      })
});


/** Field references for clean, type-safe access */
const MasterUserField = {
    Id: 'id',
    Fullname: 'fullname',
    Username: 'username',
    Password: 'password',
    AccessId: 'access_id',
    Status: 'status',
    All: ['id', 'fullname', 'username', 'password', 'access_id', 'status'],
};


module.exports = {
  MasterUserSchema,
  MasterUserField, 
};
