
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const ReceiptItemsSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	receiptsId: Joi.number().integer().required().messages({
        'any.required': 'receiptsId is required.',
        'number.base': 'receiptsId must be a valid integer.',
      }),
 	productService: Joi.string().trim().required().messages({
        'any.required': 'productService is required.',
        'string.empty': 'productService must be a valid string.',
      }),
 	chartsOfAccounts: Joi.number().integer().required().messages({
        'any.required': 'chartsOfAccounts is required.',
        'number.base': 'chartsOfAccounts must be a valid integer.',
      }),
 	description: Joi.string().trim().required().messages({
        'any.required': 'description is required.',
        'string.empty': 'description must be a valid text.',
      }),
 	unit: Joi.string().trim().required().messages({
        'any.required': 'unit is required.',
        'string.empty': 'unit must be a valid string.',
      }),
 	quantity: Joi.number().integer().required().messages({
        'any.required': 'quantity is required.',
        'number.base': 'quantity must be a valid integer.',
      }),
 	salesPrice: Joi.string().trim().required().messages({
        'any.required': 'salesPrice is required.',
        'string.empty': 'salesPrice must be a valid decimal.',
      }),
 	discount: Joi.string().trim().required().messages({
        'any.required': 'discount is required.',
        'string.empty': 'discount must be a valid decimal.',
      }),
 	vat: Joi.string().trim().required().messages({
        'any.required': 'vat is required.',
        'string.empty': 'vat must be a valid decimal.',
      }),
 	witholdingTax: Joi.string().trim().required().messages({
        'any.required': 'witholdingTax is required.',
        'string.empty': 'witholdingTax must be a valid decimal.',
      }),
 	responsibilityCenter: Joi.string().trim().required().messages({
        'any.required': 'responsibilityCenter is required.',
        'string.empty': 'responsibilityCenter must be a valid string.',
      })
});


/** Field references for clean, type-safe access */
const ReceiptItemsField = {
    Id: 'id',
    ReceiptsId: 'receipts_id',
    ProductService: 'product_service',
    ChartsOfAccounts: 'charts_of_accounts',
    Description: 'description',
    Unit: 'unit',
    Quantity: 'quantity',
    SalesPrice: 'sales_price',
    Discount: 'discount',
    Vat: 'vat',
    WitholdingTax: 'witholding_tax',
    ResponsibilityCenter: 'responsibility_center',
    All: ['id', 'receipts_id', 'product_service', 'charts_of_accounts', 'description', 'unit', 'quantity', 'sales_price', 'discount', 'vat', 'witholding_tax', 'responsibility_center'],
};


module.exports = {
  ReceiptItemsSchema,
  ReceiptItemsField, 
};
