const TaxCompliance = {
  tax_forms: {
    tablename: 'tax_forms',
    prefix: 'tf',
    prefix_: 'tf_',
    insertColumns: [
      'form_type',
      'user_id',
      'company_id',
      'start_date',
      'end_date',
      'form_data',
      'status',
    ],
    selectColumns: [
      'tf_id',
      'tf_form_type',
      'tf_user_id',
      'tf_company_id',
      'tf_start_date',
      'tf_end_date',
      'tf_form_data',
      'tf_status',
      'tf_created_at',
      'tf_updated_at',
    ],
    selectOptionColumns: {
      id: 'tf_id',
      form_type: 'tf_form_type',
      user_id: 'tf_user_id',
      company_id: 'tf_company_id',
      start_date: 'tf_start_date',
      end_date: 'tf_end_date',
      form_data: 'tf_form_data',
      status: 'tf_status',
      created_at: 'tf_created_at',
      updated_at: 'tf_updated_at',
    },
    updateOptionColumns: {
      id: 'id',
      form_type: 'form_type',
      user_id: 'user_id',
      company_id: 'company_id',
      start_date: 'start_date',
      end_date: 'end_date',
      form_data: 'form_data',
      status: 'status',
    },
    selectDateFormatColumns: {
      created_at: 'tf_created_at',
      updated_at: 'tf_updated_at',
    },
    selectMiscColumns: {},
    columnDataTypes: {
      id: 'INTEGER',
      form_type: 'STRING',
      user_id: 'INTEGER',
      company_id: 'INTEGER',
      start_date: 'DATE',
      end_date: 'DATE',
      form_data: 'JSON',
      status: 'ENUM',
      created_at: 'DATETIME',
      updated_at: 'DATETIME',
    },
  },
}

module.exports = { TaxCompliance }
