
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const MasterUserSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	username: Joi.string().trim().required().messages({
        'any.required': 'username is required.',
        'string.empty': 'username must be a valid string.',
      }),
 	password: Joi.string().trim().required().messages({
        'any.required': 'password is required.',
        'string.empty': 'password must be a valid text.',
      }),
 	dbName: Joi.string().trim().required().messages({
        'any.required': 'dbName is required.',
        'string.empty': 'dbName must be a valid string.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      })
});


/** Field references for clean, type-safe access */
const MasterUserField = {
    Id: 'id',
    Username: 'username',
    Password: 'password',
    DbName: 'db_name',
    Status: 'status',
    All: ['id', 'username', 'password', 'db_name', 'status'],
};


module.exports = {
  MasterUserSchema,
  MasterUserField, 
};
