
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const SubscriptionHistorySchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	muId: Joi.number().integer().required().messages({
        'any.required': 'muId is required.',
        'number.base': 'muId must be a valid integer.',
      }),
 	subscriptionId: Joi.number().integer().required().messages({
        'any.required': 'subscriptionId is required.',
        'number.base': 'subscriptionId must be a valid integer.',
      }),
 	price: Joi.string().trim().required().messages({
        'any.required': 'price is required.',
        'string.empty': 'price must be a valid decimal.',
      }),
 	billingCycle: Joi.string().trim().required().messages({
        'any.required': 'billingCycle is required.',
        'string.empty': 'billingCycle must be a valid string.',
      }),
 	startDate: Joi.string().isoDate().required().messages({
        'any.required': 'startDate is required.',
        'string.empty': 'startDate must be a valid date.',
      }),
 	endDate: Joi.string().isoDate().required().messages({
        'any.required': 'endDate is required.',
        'string.empty': 'endDate must be a valid date.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      }),
 	paymentMethod: Joi.string().trim().required().messages({
        'any.required': 'paymentMethod is required.',
        'string.empty': 'paymentMethod must be a valid string.',
      }),
 	paymentReference: Joi.string().trim().required().messages({
        'any.required': 'paymentReference is required.',
        'string.empty': 'paymentReference must be a valid string.',
      }),
 	createdAt: Joi.string().isoDate().required().messages({
        'any.required': 'createdAt is required.',
        'string.empty': 'createdAt must be a valid date.',
      }),
 	updatedAt: Joi.string().isoDate().required().messages({
        'any.required': 'updatedAt is required.',
        'string.empty': 'updatedAt must be a valid date.',
      })
});


/** Field references for clean, type-safe access */
const SubscriptionHistoryField = {
    Id: 'id',
    MuId: 'mu_id',
    SubscriptionId: 'subscription_id',
    Price: 'price',
    BillingCycle: 'billing_cycle',
    StartDate: 'start_date',
    EndDate: 'end_date',
    Status: 'status',
    PaymentMethod: 'payment_method',
    PaymentReference: 'payment_reference',
    CreatedAt: 'created_at',
    UpdatedAt: 'updated_at',
    All: ['id', 'mu_id', 'subscription_id', 'price', 'billing_cycle', 'start_date', 'end_date', 'status', 'payment_method', 'payment_reference', 'created_at', 'updated_at'],
};


module.exports = {
  SubscriptionHistorySchema,
  SubscriptionHistoryField, 
};
